name: Build site

"on":
  workflow_dispatch: {}
  workflow_run:
    workflows:
      - "Flat data"
    branches:
      - "main"
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '45 23 * * *'
  push:
    branches: [main]
    paths:
      - "data/**"
      - "src/**"
      - "_config.js"
      - "deno.json"
      - "import_map.json"
      - ".github/workflows/build-site.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3.1.0

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: v1.x

      - name: Build site
        run: |
          deno task build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: _site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
